// Shared barbers data — used by both BarbersPreview (home) and Barbers (full page)

export const featuredBarbers = [
  {
    id: '01',
    name: 'Tariq Al-Mansoor',
    role: 'Master Stylist & Founder',
    experience: '12+ Years Experience',
    specialty: 'Royal Fade & Beard Sculpting',
    rating: '4.9',
    reviews: '120+',
    image: '/barber1.jpg',
    instagram: 'https://instagram.com',
  },
  {
    id: '02',
    name: 'Youssef El-Haddad',
    role: 'Senior Barber',
    experience: '8 Years Experience',
    specialty: 'Hot Towel Shave & Scissors Cut',
    rating: '4.8',
    reviews: '95+',
    image: '/barber2.jpg',
    instagram: 'https://instagram.com',
  },
  {
    id: '03',
    name: 'Hamza Ibrahim',
    role: 'Grooming Specialist',
    experience: '6 Years Experience',
    specialty: 'Keratin & Executive Facials',
    rating: '4.9',
    reviews: '80+',
    image: '/barber3.jpg',
    instagram: 'https://instagram.com',
  },
]

export const allBarbers = [
  ...featuredBarbers,
  {
    id: '04',
    name: 'Omar Al-Rashidi',
    role: 'Color & Texture Specialist',
    experience: '7 Years Experience',
    specialty: 'Hair Colouring & Keratin',
    rating: '4.7',
    reviews: '70+',
    image: '/barber4.jpg',
    instagram: 'https://instagram.com',
  },
  {
    id: '05',
    name: 'Khalid Al-Zahrani',
    role: 'Classic Cuts Expert',
    experience: '5 Years Experience',
    specialty: 'Classic Taper & Hot Towel Shave',
    rating: '4.8',
    reviews: '60+',
    image: '/barber5.jpg',
    instagram: 'https://instagram.com',
  },
  {
    id: '06',
    name: 'Faisal Al-Otaibi',
    role: 'Junior Barber',
    experience: '3 Years Experience',
    specialty: 'Modern Styles & Beard Trim',
    rating: '4.6',
    reviews: '40+',
    image: '/barber6.jpg',
    instagram: 'https://instagram.com',
  },
]
